FROM ros:noetic
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq --no-install-recommends

RUN bash /opt/ros/noetic/setup.bash
RUN apt-get install -y ros-$(rosversion -d)-turtlesim

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN echo "alias python=python3" >> ~/.bashrc